### ISSUE TITLE
Units can have zero build time

### ISSUE THREAD

**Issue by lsrom** [retro-game/retro-game#40]
*Bug:* With high enough nanite factory/shipyard or just speed multiplier it is possible to build units instantaneously. This isn't possible in vanilla game.

*Fix?* All units/researches/buildings should have minimum build/research time of 1 second.

**Comment by patrykstefanski** [comment]
Buildings and technologies have the minimum time set to 1s.

Setting the minimum time of units to 1s might not work well if someone wants to build a big fleet. 0s is not good as well, since someone might build fleet instantly.

IIRC in vanilla game you could build few units in 1s and maybe this could be implemented.

**Comment by lsrom** [comment]
Vanilla had minimum time zero seconds. It makes sense because otherwise you can build enormous fleets in an instant. This is game breaking because than you can ninja attackers with the resources on your planet. One second minimum time requires you to plan ahead.
